partially update flake
nixpkgs has been left untouched because of this error:
error: Package ‘nix-linter-0.2.0.4’ in /nix/store/lzgxbh8c61phbh074y2707l2yw6vvaa1-source/pkgs/development/tools/analysis/nix-linter/default.nix:23 is marked as broken, refusing to evaluate.

additionally, nixpkgs-master has been removed - there was no real use for it